Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -97,94 +97,94 @@ jobs:
           compression-level: 0
           retention-days: 7
 
-  emu-linux-all:
-    name: "Emu linux all"
-    if: ${{ !cancelled() }}
-    uses: "./.github/workflows/emu-build-all-linux.yml"
+  # emu-linux-all:
+    # name: "Emu linux all"
+    # if: ${{ !cancelled() }}
+    # uses: "./.github/workflows/emu-build-all-linux.yml"
 
-  emu-linux-prep:
-    needs: ["emu-linux-all"]
-    runs-on: "ubuntu-22.04"
-    steps:
-      # we need branch because it has package scripts
-      - name: "Checkout branch"
-        uses: actions/checkout@v6
+  # emu-linux-prep:
+    # needs: ["emu-linux-all"]
+    # runs-on: "ubuntu-22.04"
+    # steps:
+      # # we need branch because it has package scripts
+      # - name: "Checkout branch"
+        # uses: actions/checkout@v6
 
-      - name: "Clone third-party deps (deps/linux)"
-        uses: actions/checkout@v6
-        with:
-          ref: "third-party/deps/linux"
-          path: "${{env.THIRD_PARTY_BASE_DIR}}/deps/linux"
+      # - name: "Clone third-party deps (deps/linux)"
+        # uses: actions/checkout@v6
+        # with:
+          # ref: "third-party/deps/linux"
+          # path: "${{env.THIRD_PARTY_BASE_DIR}}/deps/linux"
 
-      # download artifacts
-      - name: "Download emu build artifacts (linux)"
-        uses: actions/download-artifact@v8
-        with:
-          path: "build/linux"
-          pattern: "emu-linux-*-${{ github.sha }}"
-          merge-multiple: true
+      # # download artifacts
+      # - name: "Download emu build artifacts (linux)"
+        # uses: actions/download-artifact@v8
+        # with:
+          # path: "build/linux"
+          # pattern: "emu-linux-*-${{ github.sha }}"
+          # merge-multiple: true
 
-      # fix folder permissions! not sure why this fails
-      # nested subdirs "build/linux/release" cause permission problems
-      - name: "Give all permissions to repo folder"
-        shell: "bash"
-        working-directory: "${{ github.workspace }}"
-        run: sudo chmod -R 777 "${{ github.workspace }}" && sudo chmod 777 package_linux.sh
+      # # fix folder permissions! not sure why this fails
+      # # nested subdirs "build/linux/release" cause permission problems
+      # - name: "Give all permissions to repo folder"
+        # shell: "bash"
+        # working-directory: "${{ github.workspace }}"
+        # run: sudo chmod -R 777 "${{ github.workspace }}" && sudo chmod 777 package_linux.sh
 
-      # print files
-      - name: "Print files"
-        shell: "bash"
-        working-directory: "${{ github.workspace }}"
-        run: |
-          ls -la build/linux/*/*
+      # # print files
+      # - name: "Print files"
+        # shell: "bash"
+        # working-directory: "${{ github.workspace }}"
+        # run: |
+          # ls -la build/linux/*/*
 
-      # downlaod ubuntu packages
-      - name: "Download required Ubuntu packages"
-        shell: "bash"
-        working-directory: "${{ github.workspace }}"
-        run: |
-          sudo apt update || exit 1
-          sudo apt install tar -y || exit 1
+      # # downlaod ubuntu packages
+      # - name: "Download required Ubuntu packages"
+        # shell: "bash"
+        # working-directory: "${{ github.workspace }}"
+        # run: |
+          # sudo apt update || exit 1
+          # sudo apt install tar -y || exit 1
 
-      # package (release mode)
-      - name: "Package build (release)"
-        shell: "bash"
-        working-directory: "${{ github.workspace }}"
-        run: ./package_linux.sh gmake2/release
+      # # package (release mode)
+      # - name: "Package build (release)"
+        # shell: "bash"
+        # working-directory: "${{ github.workspace }}"
+        # run: ./package_linux.sh gmake2/release
 
-      # package (debug mode)
-      - name: "Package build (debug)"
-        shell: "bash"
-        working-directory: "${{ github.workspace }}"
-        run: ./package_linux.sh gmake2/debug 1
+      # # package (debug mode)
+      # - name: "Package build (debug)"
+        # shell: "bash"
+        # working-directory: "${{ github.workspace }}"
+        # run: ./package_linux.sh gmake2/debug 1
 
-      # release (debug + release modes) if this is a tag push
-      - name: "Release"
-        if: startsWith(github.ref, 'refs/tags/')
-        uses: softprops/action-gh-release@v2
-        with:
-          files: "build/package/linux/**/*"
+      # # release (debug + release modes) if this is a tag push
+      # - name: "Release"
+        # if: startsWith(github.ref, 'refs/tags/')
+        # uses: softprops/action-gh-release@v2
+        # with:
+          # files: "build/package/linux/**/*"
 
-      # upload artifacts/packages if this is a manual run
-      - name: "Upload release package"
-        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
-        uses: actions/upload-artifact@v7
-        with:
-          name: "release-emu-linux-release-${{ github.sha }}"
-          path: "build/package/linux/gmake2/*release*"
-          if-no-files-found: "error"
-          compression-level: 0
-          retention-days: 7
+      # # upload artifacts/packages if this is a manual run
+      # - name: "Upload release package"
+        # if: ${{ !startsWith(github.ref, 'refs/tags/') }}
+        # uses: actions/upload-artifact@v7
+        # with:
+          # name: "release-emu-linux-release-${{ github.sha }}"
+          # path: "build/package/linux/gmake2/*release*"
+          # if-no-files-found: "error"
+          # compression-level: 0
+          # retention-days: 7
 
-      - name: "Upload debug package"
-        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
-        uses: actions/upload-artifact@v7
-        with:
-          name: "release-emu-linux-debug-${{ github.sha }}"
-          path: "build/package/linux/gmake2/*debug*"
-          if-no-files-found: "error"
-          compression-level: 0
-          retention-days: 7
+      # - name: "Upload debug package"
+        # if: ${{ !startsWith(github.ref, 'refs/tags/') }}
+        # uses: actions/upload-artifact@v7
+        # with:
+          # name: "release-emu-linux-debug-${{ github.sha }}"
+          # path: "build/package/linux/gmake2/*debug*"
+          # if-no-files-found: "error"
+          # compression-level: 0
+          # retention-days: 7
 
   migrate_gse_script-win:
     name: "Migrate GSE win"
@@ -246,54 +246,54 @@ jobs:
           compression-level: 9
           retention-days: 7
 
-  migrate_gse_script-linux:
-    name: Migrate GSE linux
-    if: ${{ !cancelled() }}
-    uses: "./.github/workflows/migrate_gse-build-linux.yml"
+  # migrate_gse_script-linux:
+    # name: Migrate GSE linux
+    # if: ${{ !cancelled() }}
+    # uses: "./.github/workflows/migrate_gse-build-linux.yml"
 
-  migrate_gse_script-linux-prep:
-    needs: ["migrate_gse_script-linux"]
-    runs-on: "ubuntu-22.04"
-    steps:
-      # we need branch because it has package scripts
-      - name: "Checkout branch"
-        uses: actions/checkout@v6
+  # migrate_gse_script-linux-prep:
+    # needs: ["migrate_gse_script-linux"]
+    # runs-on: "ubuntu-22.04"
+    # steps:
+      # # we need branch because it has package scripts
+      # - name: "Checkout branch"
+        # uses: actions/checkout@v6
 
-      # download artifacts
-      - name: "Download script build artifacts (linux)"
-        uses: actions/download-artifact@v8
-        with:
-          path: "tools/migrate_gse/bin/linux"
-          pattern: "migrate_gse-linux-*"
-          merge-multiple: true
+      # # download artifacts
+      # - name: "Download script build artifacts (linux)"
+        # uses: actions/download-artifact@v8
+        # with:
+          # path: "tools/migrate_gse/bin/linux"
+          # pattern: "migrate_gse-linux-*"
+          # merge-multiple: true
 
-      # fix folder permissions! not sure why this fails
-      # nested subdirs "build/linux/release" cause permission problems
-      - name: "Give all permissions to repo folder"
-        shell: "bash"
-        working-directory: "${{ github.workspace }}"
-        run: sudo chmod -R 777 "${{ github.workspace }}"
+      # # fix folder permissions! not sure why this fails
+      # # nested subdirs "build/linux/release" cause permission problems
+      # - name: "Give all permissions to repo folder"
+        # shell: "bash"
+        # working-directory: "${{ github.workspace }}"
+        # run: sudo chmod -R 777 "${{ github.workspace }}"
 
-      # package
-      - name: "Package script"
-        shell: "bash"
-        working-directory: "tools/migrate_gse"
-        run: sudo chmod 777 package_linux.sh && sudo ./package_linux.sh
+      # # package
+      # - name: "Package script"
+        # shell: "bash"
+        # working-directory: "tools/migrate_gse"
+        # run: sudo chmod 777 package_linux.sh && sudo ./package_linux.sh
 
-      # release tag
-      - name: "Release"
-        if: startsWith(github.ref, 'refs/tags/')
-        uses: softprops/action-gh-release@v2
-        with:
-          files: "tools/migrate_gse/bin/package/linux/**/*"
+      # # release tag
+      # - name: "Release"
+        # if: startsWith(github.ref, 'refs/tags/')
+        # uses: softprops/action-gh-release@v2
+        # with:
+          # files: "tools/migrate_gse/bin/package/linux/**/*"
 
-      # upload artifact/package if this is a manual run
-      - name: "Upload release package"
-        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
-        uses: actions/upload-artifact@v7
-        with:
-          name: "release-migrate_gse-linux-${{ github.sha }}"
-          path: "tools/migrate_gse/bin/package/linux/**/*"
-          if-no-files-found: "error"
-          compression-level: 9
-          retention-days: 7
+      # # upload artifact/package if this is a manual run
+      # - name: "Upload release package"
+        # if: ${{ !startsWith(github.ref, 'refs/tags/') }}
+        # uses: actions/upload-artifact@v7
+        # with:
+          # name: "release-migrate_gse-linux-${{ github.sha }}"
+          # path: "tools/migrate_gse/bin/package/linux/**/*"
+          # if-no-files-found: "error"
+          # compression-level: 9
+          # retention-days: 7
